name: wifi-admin

services:
  api:
    image: hr-telekom/wifi-admin-api:1.0.0
    container_name: api
    depends_on:
      postgres:
        condition: service_healthy
      platform-mock:
        condition: service_started
    environment:
      AES_KEY: ${AES_KEY}
      JWT_SECRET: ${JWT_SECRET}
      SOAP_ENDPOINT: http://platform-mock:3000/platform
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: -Duser.timezone=Europe/Zagreb
    ports:
      - "8081:8081"
      - "8082:8082"

  loki:
    image: grafana/loki:3.7.3
    container_name: loki
    ports:
      - "3100"
    volumes:
      - ./docker/loki.config.yml:/etc/loki/config.yaml:ro,Z
    healthcheck:
      test: ["CMD", "loki", "-health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  alloy:
    image: grafana/alloy:v1.17.1
    container_name: alloy
    depends_on:
      loki:
        condition: service_healthy
    user: root
    ports:
      - "12345"
    security_opt:
      - label=disable
    volumes:
      - ./docker/config.alloy:/etc/alloy/config.alloy:ro,Z
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345

  grafana:
    image: grafana/grafana:13.0.3-distroless-slim
    container_name: grafana
    depends_on:
      loki:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/dashboards:/etc/grafana/dashboards:ro,Z
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro,Z

volumes:
  grafana-data:
