services:
  platform-mock:
    image: mockoon/cli:9.2.0
    container_name: platform-mock
    command:
      - --data
      - /data/platform-mock.json
      - --port
      - "3000"
      - --hostname
      - 0.0.0.0
    volumes:
      - ./mockoon/platform-mock.json:/data/platform-mock.json:ro,Z
    ports:
      - "8080:3000"

  http-echo:
    image: mendhak/http-https-echo:latest
    container_name: http-echo
    ports:
      - "8082:8080"
