set shell := ["bash", "-eu", "-o", "pipefail", "-c"]
set dotenv-load

import 'just/api.just'
import 'just/deploy.just'
import 'just/docker.just'
import 'just/server.just'

api-url := "http://localhost:8081"
actuator-url := "http://localhost:8082/actuator"

# List available recipes
default:
    @just --list

# Run Gradle
[arg("args", help="Arguments passed to Gradle")]
gradle *args:
    ./gradlew {{args}}
