[versions]
cxf = "4.2.2"
springdoc = "3.0.3"
slf4j = "2.0.18"
archunit = "1.4.2"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

cxf-tools-wsdlto-core = { module = "org.apache.cxf:cxf-tools-wsdlto-core", version.ref = "cxf" }
cxf-tools-wsdlto-frontend-jaxws = { module = "org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws", version.ref = "cxf" }
cxf-tools-wsdlto-databinding-jaxb = { module = "org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb", version.ref = "cxf" }
cxf-spring-boot-starter-jaxws = { module = "org.apache.cxf:cxf-spring-boot-starter-jaxws", version.ref = "cxf" }

springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

tngtech-archunit = { module = "com.tngtech.archunit:archunit", version.ref = "archunit" }
tngtech-archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
