{
 "title": "Docker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Backend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"api\"}"
    }
   ]
  },
  {
   "title": "SOAP Platform",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"platform-mock\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Loki",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"loki\"}"
    }
   ]
  },
  {
   "title": "Alloy",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"alloy\"}"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"grafana\"}"
    }
   ]
  }
 ]
}