{
 "title": "Backend",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Server Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"backend\"} | json | __error__ = \"\""
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"backend\"}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"backend\"}\n| json\n| logger_name =~ \"^hr\\\\.ht\\\\.rnd\\\\.wifiadmin.*\""
    }
   ]
  },
  {
   "title": "Event Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"backend\"}\n| json\n| event != \"\""
    }
   ]
  }
 ]
}