server.port=8081
spring.application.name=wifi-admin-backend

spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view= false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

cxf.log-faults=true
platform.soap-endpoint=http://localhost:8080/platform
platform.cpe-id-format=CPE_%03d
platform.cpe-id-count=12
platform.sync-on-startup=true
platform.sync-schedule=00:00
security.aes-key=${AES_KEY}
security.jwt-secret=${JWT_SECRET}
security.jwt-expiration=PT1H
security.allowed-origins=http://localhost:5173
security.public-endpoints=/auth/login
