spring.main.banner-mode=off
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:tc:postgresql:16-alpine:///wifi-admin-backend
spring.datasource.hikari.maximum-pool-size=2

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
