spring.main.banner-mode=off
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:tc:postgresql:16-alpine:///wifi-admin-backend
spring.datasource.hikari.maximum-pool-size=2

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

cxf.log-faults=false

platform.soap-endpoint=http://localhost
platform.sync-on-startup=false
security.aes-key=MAvyARneD9vfVvbEFn7K95iE02t7AtMs8Fpo6z5d/2k=
security.jwt-secret=hwr3ugS1/biZ/uZ35fYe0hnRm7exGm5qe3mBJDOQwns=
